[API]
url=https://clinicaadventista.markey.com.ar/APIMarkeyCAB
APIKey=d5e75bde-205b-4468-86ec-67e7160bad2e
urlTC=http://10.99.8.106/cab/public/v2
tokenAcceso=cv44uu1depYrgYVwq7S6W7wC0F2OfjbZQvJ9Ay4wqY8qn1jDufmfZszW2V8bnnSasGtHJMQyBVjQzZGC361iOMZGEU9jYTFUYxv2jZ6yZh7QoHEfb59kWgohM1FoB5aB

[SQL]
servidor=10.99.8.8
base=CAB
usuario=superusr_cab

[TABLERO]
servicio=1
columnas=5
altura=145
padding=5
actualizar=30
fullscreen=0
;alertas=1
dias=1
autologin=0
versolotareaspendientes=0
cambiarServicios=1

[INTERNACIONES_PENDIENTES]
horas=24

[UPDATE]
1=\\10.99.8.108\aplicaciones\tablerocamas\ultima_version
2=c:\tc
